#
# Copyright (c) 2019-2024 smallprogram
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/smallprogram/OpenWrtAction
# File: .github/workflows/Update_Checker.yml
# Description: Source code update checker
#

name: Update_Checker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 */3 * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Get Commit Hash
      id: getHash
      run: |
        # 克隆并获取 ImmortalWrt 的 Commit Hash
        git clone -b openwrt-25.12 https://github.com/immortalwrt/immortalwrt immortalwrt --filter=blob:none
        cd immortalwrt
        echo "SHA_01=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        cd

        # 克隆并获取 OpenWrt-Passwall 的 Commit Hash
        git clone -b main https://github.com/Openwrt-Passwall/openwrt-passwall.git openwrt-passwall --filter=blob:none
        cd openwrt-passwall
        echo "SHA_02=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        cd

    - name: Show Commit Head and Combination Heads
      id: combHeader
      run: |
        # 组合两个仓库的 Hash 值，任何一个发生变化都会改变组合值
        echo "commitHash_All=\
          ${{steps.getHash.outputs.SHA_01}}-\
          ${{steps.getHash.outputs.SHA_02}}" >> $GITHUB_OUTPUT

    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@v5
      with:
        path: .commitHash_All
        key: HEAD-${{ steps.combHeader.outputs.commitHash_All }}
   
    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.combHeader.outputs.commitHash_All }} | tee .commitHash_All
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 3

    - name: Trigger build
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v4
      with:
        token: ${{ secrets.OP_UPDATE  }}
        event-type: openwrt_source_update
